global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'credit-score-monitor'

# Configuration d'alerting Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:

# Charger les fichiers de règles
rule_files:
  # - "alert_rules.yml"

# Scrape Configs
scrape_configs:
  # Scraper Prometheus lui-même
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # Scraper l'API Credit Score
  - job_name: 'credit-score-api'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__scheme__]
        target_label: scheme
